sudo: required
services:
  - docker

before_install:
  - docker build -t ella-harris/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ella-harris/react-test npm run test

after_success:
  - docker build -t ella-harris/multi-client ./client
  - docker build -t ella-harris/multi-nginx ./nginx
  - docker build -t ella-harris/multi-server ./server
  - docker build -t ella-harris/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
  - docker push ellah/multi-client
  - docker push ellah/multi-nginx
  - docker push ellah/multi-server
  - docker push ellah/multi-worker


